base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('restapi/', include('restapi.urls')),
    path('', include('shop.urls'))
    # path('', include('homepage.urls'))
]

restapi/urls.py
from restapi.models import CourceResource, CategoryResource
from tastypie.api import Api
from django.urls import path, include

api = Api(api_name='v1')
api.register(CourceResource())
api.register(CategoryResource())

# For POST, DELETE add header
# Key: Authorization
# Value: ApiKey alex:170976

urlpatterns = [
    path('', include(api.urls), name='index')
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('course/<int:course_id>', views.single_course, name='single_course')

]

restapi/models.py
from tastypie.resources import ModelResource
from shop.models import Category, Course
from tastypie.authorization import Authorization
from .authentication import CustomAuthentication


class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get']


class CourceResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allowed_methods = ['get', 'post', 'delete']
        excludes = ['reviews_qty', 'created_at']
        authentication = CustomAuthentication()
        authorization = Authorization()

    def hydrate(self, bundle):
        bundle.obj.cetegory_id = bundle.data['cetegory_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['cetegory_id'] = bundle.obj.cetegory_id
        bundle.data['cetegory'] = bundle.obj.cetegory
        return bundle

    def dehydrate_title(self, bundle):
        return bundle.data['title'].upper()

shop/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField(max_length=255)
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    cetegory = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

restapi/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Course


def index(request):
    courses = Course.objects.all()
    return render(request, 'shop/courses.html', {'courses': courses})


def single_course(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'shop/single_course.html', {'course': course})

shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href="" class="navbar-brand">Courses Shop</a>
        </div>
    </nav>
    <main class="container">
        {% block content %}{% endblock %}
    </main>    
</body>
</html>

shop/templates/courses.html
{% extends 'base.html' %}
{% block title %}All courses{% endblock %}

{% block content %}
<table class="table mt-5 table-border table-striped table-hover">
    <thead class="table-dark">        
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Price</th>
            <th>Students Quantity</th>
            <th></th>
        </tr>        
    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <th>{{course.title}}</th>
            <th>{{course.cetegory}}</th>
            <th>{{course.price}}</th>
            <th>{{course.students_qty}}</th>
            <td><button class="btn btn-primary">Buy</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href={% url "shop:index" %} class="navbar-brand">Courses Shop</a>
            <span class="navbar-text">
                <a href="/admin/" class="me-2" target="_blak">Admin</a>
                <a href="/restapi/v1/" target="_blak">API</a>
            </span>
        </div>
    </nav>
    <main class="container">
        {% block content %}{% endblock %}
    </main>    
</body>
</html>

templates/shop/courses.html
{% extends 'base.html' %}
{% block title %}All courses{% endblock %}

{% block content %}
<table class="table mt-5 table-border table-striped table-hover">
    <thead class="table-dark">        
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Price</th>
            <th>Students Quantity</th>
            <th></th>
        </tr>        
    </thead>
    <tbody>
        {% for course in courses %}
        <tr>            
            <td>
                <a href={% url "shop:single_course" course.id %}>{{course.title}}</a>
            </td>
            <td>{{course.cetegory}}</td>
            <td>{{course.price}}</td>
            <td>{{course.students_qty}}</td>
            <td><button class="btn btn-primary">Buy</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/shop/single_course.html
{% extends 'base.html'%}

{% block title%}{{ course.title }}{% endblock %}

{% block content %}
<h1 class="mt-5">{{ course.title}}</h1>
<h2>{{ course.category }}</h2>
<p>Prise: {{ course.price }}</p>
<p>Students Quantity: {{ course.students_qty }}</p>
<button class="btn btn-primary">Buy</button>
{% endblock %}